### PR TITLE
Add version

### PR DESCRIPTION
**Pull request by zorkian**
This is a protocol breaking change to add a version number. This
will hopefully enable us to make future changes in a way that won't
necessarily break the protocol.

### CODE REVIEW

**Comment by zorkian** [comment]
I think this one breaking change needs to happen, then in the future we can make non-breaking changes. As long as we're only adding fields to the messages, or adding message types, then older versions can always parse messages destined for newer versions.

Of course, the devil is always in the details. Making code that is resilient to that, and algorithms that work in all of those cases, will be non-trivial as time goes on.

**Comment by zorkian** [comment]
PS cc @drtall

**Comment by DrTall** [comment]
This is like when PG&E calls and says "In order to avoid service interruptions, we are turning off your power." :)

This is already getting pretty complicated, you might consider switching it to an actual structured format like protobuf or avro or whatever.

LGTM

**Comment by zorkian** [comment]
Yeah, agreed.

**Pull request merged**
